Add JsonRPC protocol contract
flashbots/suave-std pull request #43
Opened 2024-02-06 18:20 UTC by ferranbt

This PR introduces a JsonRPC protocol contract to call the Ethereum JsonRPC endpoints. This PR implements the get nonce endpoint.

2024-02-06 18:26 UTC, dmarzzz requested changes

2024-02-06 18:26 UTC, dmarzzz commented on src/protocols/JsonRPC.sol
> +contract JsonRPC {
we should call this EthJsonRPC I think?

2024-02-06 18:43 UTC, ferranbt commented on src/protocols/JsonRPC.sol
> +contract JsonRPC {
Done

2024-02-14 13:46 UTC, metachris commented on README.md
> +        JsonRPC jsonrpc = new JsonRPC("http://...");
```suggestion
        JsonRPC jsonrpc = new EthJsonRPC("http://...");
```

2024-02-14 14:04 UTC, ferranbt commented on README.md
> +        JsonRPC jsonrpc = new JsonRPC("http://...");
Fixed

2024-02-19 17:42 UTC, dmarzzz approved these changes

2024-02-19 17:45 UTC, merged